$debug requires Data::Dumper
If you enable $debug = 1, then the module will crash because Data::Dumper is not used with this message:

parse_error: Undefined subroutine &AnyEvent::Discord::Client::Dumper called at ...AnyEvent/Discord/Client.pm line 178